#!/bin/bash

function usageBuild() {
    cat <<eom
Usage: saiku build
编译所有项目
eom
}

function usageRun() {
    cat <<eom
Usage: saiku build | dev

jetty: 简洁方式启动
eom
}

function start_ui(){
    kill -9 `lsof -i:9988 | grep node | awk '{print $2}'`
    kill -9 `lsof -i:35729 | grep grunt | awk '{print $2}'`
    cd saiku-ui
    npm run start2 &
    grunt &
    cd -
}
case $1 in
    "build")
        mvn clean install -DskipTests=true
        ;;

     dev)
       start_ui
          cd obobd-web
        mvn clean install -DskipTests=true -e
        mvn -e jetty:run-exploded
        ;;
    "ui")
       start_ui
        ;;
    *)
        echo "-----------------------------------------------------"
        echo "	E R R O R : Invalid option: $1" >&2
        echo "-----------------------------------------------------"
        echo ""
        usageBuild
        usageRun
        exit 1
        ;;

esac

