#!/bin/bash

function usageBuild() {
    cat <<eom
Usage: saiku build
编译所有项目
eom
}

function usageRun() {
    cat <<eom
Usage: saiku tom | jetty
tom: 原始方式启动
jetty: 简洁方式启动
eom
}

function start_ui(){
    kill -9 `lsof -i:9988 | grep node | awk '{print $2}'`
    kill -9 `lsof -i:35729 | grep grunt | awk '{print $2}'`
    cd saiku-ui
    npm run start2 &
    grunt &
    cd -
}
case $1 in
    "build")
        mvn clean install -DskipTests=true
        ;;
    "tom")
        mvn clean install -DskipTests=true -e -o
        echo ""
        echo "Running Server....."
        cd saiku-ui
        kill -9 `lsof -i:9999 | awk '{print $2}'`
        npm start &

        cd -
        cd saiku-server/target/dist/saiku-server/
        kill -9 `lsof -i:8080 | awk '{print $2}'`
        sh start-saiku.sh
        tail -f tomcat/logs/catalina.out &
        tail -f tomcat/logs/saiku.log &
        ;;
    jetty | dev)
        start_ui
        cd saiku-core
        mvn  clean install -DskipTests=true -e 
        cd -
        cd obobd-web
        mvn  clean install -e
        mvn -e jetty:run-exploded
        ;;
    "ui")
       start_ui
        ;;
    *)
        echo "-----------------------------------------------------"
        echo "	E R R O R : Invalid option: $1" >&2
        echo "-----------------------------------------------------"
        echo ""
        usageBuild
        usageRun
        exit 1
        ;;
esac

