#!/bin/bash

#
# Copyright (c) 2011 OSBI Ltd.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation 
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE 
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#


function usageBuild() {
    cat <<eom
Usage: saiku build <all | project>
  Builds all or an individual saiku project

  Example:
  saiku build all

  Others:
  saiku build < all | ui | server | webapp | bi-platform-plugin >
eom
}

function usageRun() {
    cat <<eom
Usage: saiku run <package>

package can be:

  server <start|stop>
            starts or stops the server, according to the argument

  ui [port] [backend_host] [backend_port]
      Executes node saiku-ui/server.js [port] [backend_host] [backend_port]
      Default is:
        node server.js 8080 dev.analytical-labs.com 80
eom
}

case $1 in
    "build")
        mvn clean install -DskipTests=true
        ;;
    "run")
        mvn clean install -DskipTests=true -e -o
 
        echo ""
        echo "Running Server....."
        cd saiku-server/target/dist/saiku-server/
        kill -9 `ps -a | grep java | awk '{print $1}'`
        sh start-saiku.sh
        tail -f saiku-server/target/dist/saiku-server/tomcat/logs/catalina.out&
        tail -f saiku-server/target/dist/saiku-server/tomcat/logs/saiku.log& 
        ;;
    *)
        echo "-----------------------------------------------------"
        echo "	E R R O R : Invalid option: $1" >&2
        echo "-----------------------------------------------------"
        echo ""
        usageBuild
		    usageRun
		    exit 1
	      ;;

esac

