#!/bin/bash

function do_build(){
    cd saiku-core
    mvn -DskipTests -Dmaven.test.failure.ignore=true clean install
    pause
    cd ..
    cd saiku-webapp
    mvn clean install
    pause
    cd ..
    #git submodule init
    #git submodule update
    #cd saiku-ui
    #git pull
    #git checkout 3.0.1-SNAPSHOT
    #git pull origin 3.0.1-SNAPSHOT
    # $git subtree pull --prefix=saiku-ui
    cd ../saiku-ui
    npm install
    mvn clean package install:install-file -Dfile=target/saiku-ui-3.0.1-SNAPSHOT.war  -DgroupId=org.saiku -DartifactId=saiku-ui -Dversion=3.0.1-SNAPSHOT -Dpackaging=war
    pause
    cd ../saiku-server
    mvn clean package
}

function do_upgrade(){
    cp -R ../saiku-ui src/main/webapp/
    cp ../saiku-webapp/target/saiku-webapp-3.0.10-SNAPSHOT/WEB-INF/*.xml src/main/webapp/WEB-INF/
}

function do_run(){
    cw kill 8015

    mvn -o install
    mvn tomcat:run &
}

function do_start_ui(){
    cw kill 80
    cd ../saiku-ui
    node server.js 80 localhost 8015
}



for OPT in $@ ; do

    echo "开始执行： $OPT"

    case $OPT in
        upgrade)
            do_upgrade
            ;;
        run)
            do_run
            ;;
        ui)
            do_start_ui
            ;;
        all)
            ;;
        help)
            do_help
            ;;
    esac

done
